package main

import	(
	"encoding/json"
	"fmt"
	"github.com/jmcvetta/neoism"
)

type AutoGenerated struct {
	Service string `json:"_service"`
	Version string `json:"_version"`
	ServiceResponse struct {
		ResponseInfo struct {
			HostCode string `json:"host_code"`
			HostDescription string `json:"host_description"`
		} `json:"response_info"`
		TransactionInfo struct {
			TimeStamp string `json:"time_stamp"`
			RequestID string `json:"request_id"`
			TransactionNo string `json:"transaction_no"`
		} `json:"transaction_info"`
		User struct {
			Mdn string `json:"mdn"`
		} `json:"user"`
		PartnerInfo []struct {
			Code string `json:"code"`
			Name string `json:"name"`
		} `json:"partner_info"`
		Params struct {
			Param1 string `json:"param1"`
			Param2 string `json:"param2"`
			Param3 string `json:"param3"`
			Param4 string `json:"param4"`
			Param5 string `json:"param5"`
		} `json:"params"`
		Hotel struct {
			MetaData struct {
				Latitude string `json:"latitude"`
				Longitude string `json:"longitude"`
				CountryCode string `json:"country_code"`
				Country string `json:"country"`
				HotelStar []struct {
					Star string `json:"star"`
					Total string `json:"total"`
				} `json:"hotel_star"`
				HotelType []struct {
					Type string `json:"type"`
					Total string `json:"total"`
				} `json:"hotel_type"`
				Amenities []struct {
					Aminity string `json:"aminity"`
					Total string `json:"total"`
				} `json:"amenities"`
				Location []struct {
					AreaCode string `json:"area_code"`
					Area string `json:"area"`
				} `json:"location"`
			} `json:"meta_data"`
			HotelList []struct {
				Code string `json:"code"`
				Name string `json:"name"`
				ImageURL string `json:"image_url"`
				URL string `json:"url"`
				Rating string `json:"rating"`
				ActualPrice string `json:"actual_price"`
				DiscountedPrice string `json:"discounted_price"`
				TotalRooms string `json:"total_rooms"`
				CountryName string `json:"country_name"`
				LocationID string `json:"location_id"`
				Latitude string `json:"latitude"`
				Longitude string `json:"longitude"`
				Priority string `json:"priority"`
				HotelType []string `json:"hotel_type"`
				Facilities []string `json:"facilities"`
				City string `json:"city"`
				CityID string `json:"city_id"`
				Location string `json:"location"`
				OfferText string `json:"offer_text"`
				PartnerValue string `json:"partner_value"`
				Shortlisted string `json:"shortlisted"`
			} `json:"hotel_list"`
		} `json:"hotel"`
	} `json:"service_response"`
}

func hotel_data_insert(jsonbody []byte){
	dil := AutoGenerated{}
	json.Unmarshal([]byte(jsonbody), &dil)

	for i := range dil.ServiceResponse.Hotel.HotelList{
   	s1:=dil.ServiceResponse.Hotel.HotelList[i].Name
		s2:=dil.ServiceResponse.Hotel.HotelList[i].Latitude
		s3:=dil.ServiceResponse.Hotel.HotelList[i].Longitude
		s4:=dil.ServiceResponse.Hotel.HotelList[i].ActualPrice
		s5:=dil.ServiceResponse.Hotel.HotelList[i].TotalRooms
		s6:=dil.ServiceResponse.Hotel.HotelList[i].ImageURL
		s7:=dil.ServiceResponse.Hotel.HotelList[i].OfferText
		s8:=dil.ServiceResponse.Hotel.HotelList[i].CityID
		s9:=dil.ServiceResponse.Hotel.HotelList[i].DiscountedPrice
		s10:=dil.ServiceResponse.Hotel.HotelList[i].Code
		var n *neoism.Node
		n = createHotelNode(s1,s2,s3,s4,s5,s6,s7,s8,s9,s10)
		fmt.Println(n)
	}

}
